In [5]:
import sklearn
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.naive_bayes import CategoricalNB
import math 
sklearn.__version__

'0.22.2.post1'

In [2]:
data = pd.read_csv('data/student.csv', sep=',')
msk = np.random.rand(len(data)) < 0.8

Y = data['Grade']
X = data.drop(columns=['Grade'])
X = X.apply(lambda feature: pd.factorize(feature)[0])

X_train = X[msk]
X_test = X[~msk]
Y_train = Y[msk]
Y_test = Y[~msk]

In [3]:
model = CategoricalNB()
model.fit(X_train, Y_train)
predict = model.predict(X_test)

In [4]:
# accuracy 
print (classification_report(Y_test, predict,digits = 6))
print (confusion_matrix(Y_test, predict))
print (accuracy_score(Y_test, predict))

              precision    recall  f1-score   support

           A   0.363636  0.285714  0.320000        14
          A+   0.000000  0.000000  0.000000         3
           B   0.312500  0.250000  0.277778        20
           C   0.218750  0.291667  0.250000        24
           D   0.488372  0.525000  0.506024        40
           F   0.476190  0.416667  0.444444        24

    accuracy                       0.376000       125
   macro avg   0.309908  0.294841  0.299708       125
weighted avg   0.380435  0.376000  0.375545       125

[[ 4  0  2  8  0  0]
 [ 1  0  2  0  0  0]
 [ 4  0  5  7  3  1]
 [ 1  1  5  7 10  0]
 [ 1  0  0  8 21 10]
 [ 0  1  2  2  9 10]]
0.376


End